apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cloud-node
  name: cloud-node
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cloud-node
    spec:
      containers:
      - image: chadhart/tensorflow-object-detection:runserver
        name: cloud-node
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: cloud-node-claim0
        - mountPath: /code/static
          name: cloud-node-claim1
      restartPolicy: Always
      volumes:
      - name: cloud-node-claim0
        persistentVolumeClaim:
          claimName: cloud-node-claim0
      - name: cloud-node-claim1
        persistentVolumeClaim:
          claimName: cloud-node-claim1
status: {}
