apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: edge-poc
spec:
  secretName: edge-poc-tls
  issuerRef:
    name: letsencrypt
  commonName: videostreom.losvegos.edge.konteno.warks
  dnsNames:
  - videostreom.losvegos.edge.konteno.works
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - videostream.losvegos.edge.kontena.works
  tls: 
    - hosts: 
      - videostreom.losvegos.edge.konteno.works 
      secretName: edge-poc-tls 
